/**
 * Skills that job postings name outright, used to tell what a posting asks for. It is a fixed
 * list, so a skill missing from it is simply not counted; it never invents a requirement.
 * Entries are matched as whole words, case-insensitively.
 */
const VOCABULARY = [
  // Languages and runtimes
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C#',
  'C++',
  'Go',
  'Rust',
  'PHP',
  'Ruby',
  'Kotlin',
  'Swift',
  'Dart',
  'Scala',
  'R',
  'SQL',
  'Bash',
  'Node.js',
  '.NET',
  // Web and mobile
  'React',
  'Next.js',
  'Vue.js',
  'Angular',
  'Svelte',
  'HTML',
  'CSS',
  'Tailwind',
  'Redux',
  'GraphQL',
  'REST',
  'Express.js',
  'NestJS',
  'Django',
  'Flask',
  'FastAPI',
  'Laravel',
  'Spring Boot',
  'Ruby on Rails',
  'WordPress',
  'Flutter',
  'React Native',
  'Android',
  'iOS',
  // Data
  'PostgreSQL',
  'MySQL',
  'MongoDB',
  'Redis',
  'Elasticsearch',
  'SQLite',
  'Oracle',
  'SQL Server',
  'Kafka',
  'Airflow',
  'Spark',
  'Hadoop',
  'dbt',
  'Snowflake',
  'BigQuery',
  'Power BI',
  'Tableau',
  'Excel',
  'pandas',
  'NumPy',
  'TensorFlow',
  'PyTorch',
  'machine learning',
  'data analysis',
  'data visualisation',
  'statistics',
  'ETL',
  // Cloud and operations
  'AWS',
  'Azure',
  'Google Cloud',
  'GCP',
  'Docker',
  'Kubernetes',
  'Terraform',
  'Ansible',
  'Linux',
  'CI/CD',
  'GitHub Actions',
  'Jenkins',
  'Git',
  'Nginx',
  'microservices',
  'serverless',
  'monitoring',
  'networking',
  'cybersecurity',
  'DevOps',
  // Product, design and delivery
  'Figma',
  'UX research',
  'UI design',
  'product management',
  'Agile',
  'Scrum',
  'Jira',
  'user research',
  'prototyping',
  'accessibility',
  // Business, finance and operations
  'project management',
  'budgeting',
  'financial reporting',
  'accounting',
  'bookkeeping',
  'QuickBooks',
  'SAP',
  'auditing',
  'procurement',
  'supply chain',
  'logistics',
  'inventory',
  'customer service',
  'sales',
  'business development',
  'marketing',
  'digital marketing',
  'SEO',
  'content writing',
  'copywriting',
  'social media',
  'CRM',
  'Salesforce',
  'HubSpot',
  'monitoring and evaluation',
  'grant writing',
  'fundraising',
  'report writing',
  'data entry',
  'human resources',
  'recruitment',
  'payroll',
  'training',
  'public speaking',
  'negotiation',
  // Languages people work in
  'English',
  'French',
  'Kiswahili',
  'Swahili',
  'Arabic',
  'Portuguese',
] as const;

const PATTERNS: ReadonlyArray<readonly [skill: string, pattern: RegExp]> = VOCABULARY.map(
  (skill) => {
    const escaped = skill.toLowerCase().replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    return [skill, new RegExp(`(?<![a-z0-9])${escaped}(?![a-z0-9+#])`)] as const;
  },
);

// "R" and "Go" are also ordinary words or letters, so they only count beside a clear cue.
const AMBIGUOUS: Readonly<Record<string, RegExp>> = {
  R: /\b(?:r programming|r studio|rstudio|\br\b(?=\s*(?:,|and|or|\/)\s*(?:python|sql|sas|stata)))/,
  Go: /\b(?:golang|go\s+(?:developer|engineer|programming|language|services))/,
};

/** The vocabulary skills a text names, in vocabulary order. */
export function findSkillsIn(text: string): string[] {
  const haystack = text.toLowerCase();
  return PATTERNS.filter(([skill, pattern]) =>
    skill in AMBIGUOUS ? AMBIGUOUS[skill]?.test(haystack) : pattern.test(haystack),
  ).map(([skill]) => skill);
}
