/**
 * Re-checks every board in the registry and rewrites data/boards.json and docs/BOARDS.md.
 * Run with `pnpm boards:verify`. A board is:
 *   live     its homepage (and feed, if it has one) answered
 *   blocked  it answered 202/401/403/406/429, which means "up, but refuses automated checks"
 *   down     it did not answer, or answered with another error
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { atsApiUrl } from '../providers/ats.js';
import { COUNTRIES } from './countries.js';
import { type Board, loadBoards, REGISTRY_URL } from './registry.js';

const BROWSER_UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';
const TIMEOUT_MS = 20_000;
const CONCURRENCY = 8;
const RETRIES_BEFORE_DOWN = 2;
const RETRY_DELAY_MS = 3_000;
const BLOCKED_STATUSES = new Set([202, 401, 403, 406, 429]);
const DOCS_PATH = fileURLToPath(new URL('../../../docs/BOARDS.md', import.meta.url));

async function httpStatus(url: string): Promise<number> {
  try {
    const response = await fetch(url, {
      headers: { 'user-agent': BROWSER_UA, accept: '*/*' },
      signal: AbortSignal.timeout(TIMEOUT_MS),
      redirect: 'follow',
    });
    await response.body?.cancel();
    return response.status;
  } catch {
    return 0;
  }
}

function classify(status: number): Board['status'] {
  if (status >= 200 && status < 300 && status !== 202) return 'live';
  if (BLOCKED_STATUSES.has(status)) return 'blocked';
  return 'down';
}

async function checkBoard(board: Board): Promise<Board['status']> {
  const target =
    board.access.type === 'rss'
      ? board.access.feedUrl
      : board.access.type === 'ats'
        ? atsApiUrl(board)
        : board.url;
  // One slow answer is not an outage, so a source is only "down" after failing twice.
  for (let attempt = 1; attempt <= RETRIES_BEFORE_DOWN; attempt += 1) {
    const result = classify(await httpStatus(target));
    if (result !== 'down') return result;
    await new Promise((resolve) => setTimeout(resolve, RETRY_DELAY_MS));
  }
  return 'down';
}

function describeCountries(board: Board): string {
  return board.countries
    .map((code) => {
      if (code === 'PAN') return 'Pan-African';
      if (code === 'REMOTE') return 'Remote (worldwide)';
      return COUNTRIES[code] ?? code;
    })
    .join(', ');
}

function describeAccess(board: Board): string {
  if (board.access.type === 'rss') return 'Scanned (RSS)';
  if (board.access.type === 'api') return 'Scanned (API)';
  if (board.access.type === 'ats') return 'Scanned (employer careers API)';
  return 'Link-out';
}

function renderDocs(boards: Board[], checkedAt: string): string {
  const count = (status: Board['status']) => boards.filter((b) => b.status === status).length;
  const scanned = boards.filter((b) => b.access.type !== 'listing' && b.status === 'live').length;
  const rows = [...boards]
    .sort(
      (a, b) =>
        describeCountries(a).localeCompare(describeCountries(b)) || a.name.localeCompare(b.name),
    )
    .map(
      (b) =>
        `| [${b.name}](${b.url}) | ${describeCountries(b)} | ${b.category} | ${describeAccess(b)} | ${b.status} | ${b.note ?? ''} |`,
    );
  return [
    '# Job boards',
    '',
    `_Generated by \`pnpm boards:verify\` on ${checkedAt}. Do not edit by hand; edit \`server/data/boards.json\`._`,
    '',
    `${boards.length} boards: ${count('live')} live, ${count('blocked')} blocked, ${count('down')} down. ${scanned} are scanned automatically.`,
    '',
    '- **Scanned** boards publish an RSS feed or a public API, which KaziScout reads. Employers are read through the public API of their hiring system (Greenhouse, Lever or Ashby).',
    '- **Link-out** boards have no public feed. KaziScout lists them and opens them in your browser; it never scrapes them.',
    '- **blocked** means the site is up but refuses automated checks, so it could only be confirmed in a browser.',
    '',
    '| Board | Coverage | Category | Access | Status | Note |',
    '|---|---|---|---|---|---|',
    ...rows,
    '',
  ].join('\n');
}

const boards = loadBoards();
const checkedAt = new Date().toISOString().slice(0, 10);
const queue = [...boards];
const changes: string[] = [];

await Promise.all(
  Array.from({ length: CONCURRENCY }, async () => {
    for (let board = queue.shift(); board !== undefined; board = queue.shift()) {
      const status = await checkBoard(board);
      if (status !== board.status) changes.push(`${board.id}: ${board.status} -> ${status}`);
      board.status = status;
      board.checkedAt = checkedAt;
    }
  }),
);

// Keep the registry's own key order by patching the parsed file instead of re-serialising boards.
const registry = JSON.parse(readFileSync(REGISTRY_URL, 'utf8')) as Board[];
const byId = new Map(boards.map((board) => [board.id, board]));
for (const entry of registry) {
  const checked = byId.get(entry.id);
  if (!checked) continue;
  entry.status = checked.status;
  entry.checkedAt = checked.checkedAt;
}
writeFileSync(REGISTRY_URL, `${JSON.stringify(registry, null, 2)}\n`);
writeFileSync(DOCS_PATH, renderDocs(boards, checkedAt));

process.stdout.write(
  `Checked ${boards.length} boards. ${changes.length} changed status.\n${changes.join('\n')}${changes.length > 0 ? '\n' : ''}`,
);
